### PR TITLE
Refactor unused

### PR DESCRIPTION
**Pull request by HarrisJT**
This messes with the git history (just changes the hashses) in order to remove "location_parser/business.json". This merge also removes unused folders/files

### CODE REVIEW

**Comment by HarrisJT** [comment]
HMMMMMM, this seems to double the amount of commits. I was thinking they would be overwritten. I'm not sure how this works. Still I think this should get merged

**Comment by elliotBraem** [comment]
Business.json is not on the develop branch in the first place. Why not just one commit to remove the unnecessary files?

**Comment by HarrisJT** [comment]
@elliotBraem because when I pull develop it gives me the file. I have no idea how

**Comment by HarrisJT** [comment]
I know, I just don't know what else to do. I can't pull develop

**Comment by elliotBraem** [comment]
git fetch --prune
git checkout develop
git reset --hard origin develop

Maybe?

I don't think this pull request is gonna fix it, all the important stuff is
done and on develop that you had changed yesterday, so you can reset --hard
your local

**Comment by HarrisJT** [comment]
idk, I deleted the file using git rm, and I did the reset hard which probably helped. #61 is the new pull request

**Pull request closed without merging**
